app = "tex-backend"  # <-- YOU CAN RENAME THIS, but it must be unique

primary_region = "iad"  # or your closest region

[build]
  dockerfile = "Dockerfile"
  target = "tex-core"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0